//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SQL.Loc.OTPCaptureViewer.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SQL.Loc.OTPCaptureViewer.Resx.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please load picture first!.
        /// </summary>
        internal static string EditCapture_LoadScreenshotFirst_Message {
            get {
                return ResourceManager.GetString("EditCapture_LoadScreenshotFirst_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the edited picture?.
        /// </summary>
        internal static string EditCapture_SaveConfirmation_Message {
            get {
                return ResourceManager.GetString("EditCapture_SaveConfirmation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected!.
        /// </summary>
        internal static string GitHub_Connect_Message {
            get {
                return ResourceManager.GetString("GitHub_Connect_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to GitHub!.
        /// </summary>
        internal static string GitHub_ConnectFail_Message {
            get {
                return ResourceManager.GetString("GitHub_ConnectFail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token is empty!.
        /// </summary>
        internal static string GitHub_EmptyToken_Message {
            get {
                return ResourceManager.GetString("GitHub_EmptyToken_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub is not connected!.
        /// </summary>
        internal static string GitHub_NotConnected_Message {
            get {
                return ResourceManager.GetString("GitHub_NotConnected_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the last capture!.
        /// </summary>
        internal static string LoadCapture_LastScreenshot_Message {
            get {
                return ResourceManager.GetString("LoadCapture_LastScreenshot_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No screenshots found!.
        /// </summary>
        internal static string LoadCapture_NoScreenshotFound_Message {
            get {
                return ResourceManager.GetString("LoadCapture_NoScreenshotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find the file in the selected folder..
        /// </summary>
        internal static string LookupCapture_CaptureNotFind_Message {
            get {
                return ResourceManager.GetString("LookupCapture_CaptureNotFind_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No captures found under the selected folder. Please check whether you have set the access correctly for the GitHub token..
        /// </summary>
        internal static string Main_NoCaptureFoundError_Message {
            get {
                return ResourceManager.GetString("Main_NoCaptureFoundError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is empty!.
        /// </summary>
        internal static string NewIssue_EmptyDescription_Message {
            get {
                return ResourceManager.GetString("NewIssue_EmptyDescription_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is empty!.
        /// </summary>
        internal static string NewIssue_EmptyTitle_Message {
            get {
                return ResourceManager.GetString("NewIssue_EmptyTitle_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit failed!.
        /// </summary>
        internal static string NewIssue_SubmitFail_Message {
            get {
                return ResourceManager.GetString("NewIssue_SubmitFail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit failed! The exception is: {0}.
        /// </summary>
        internal static string NewIssue_SubmitFailError_Message {
            get {
                return ResourceManager.GetString("NewIssue_SubmitFailError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted!.
        /// </summary>
        internal static string NewIssue_SubmitSuccess_Message {
            get {
                return ResourceManager.GetString("NewIssue_SubmitSuccess_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an issue!.
        /// </summary>
        internal static string OpenIssue_MustSelectAnIssue_Message {
            get {
                return ResourceManager.GetString("OpenIssue_MustSelectAnIssue_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no capture for linguistic review in this folder!.
        /// </summary>
        internal static string RepoBrowser_FolderNotReady_Message {
            get {
                return ResourceManager.GetString("RepoBrowser_FolderNotReady_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a folder!.
        /// </summary>
        internal static string RepoBrowser_FolderNotSelected_Message {
            get {
                return ResourceManager.GetString("RepoBrowser_FolderNotSelected_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log result to result file failed! It may be used by another process. Please close the process which is using this file and try again..
        /// </summary>
        internal static string ReviewCapture_OpenResultFileFail_Message {
            get {
                return ResourceManager.GetString("ReviewCapture_OpenResultFileFail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save result failed!.
        /// </summary>
        internal static string ReviewCapture_SaveResultFail_Message {
            get {
                return ResourceManager.GetString("ReviewCapture_SaveResultFail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to create the folder!.
        /// </summary>
        internal static string Settings_LogFolderCreateFail_Message {
            get {
                return ResourceManager.GetString("Settings_LogFolderCreateFail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log folder does not exist. Do you want to create it?.
        /// </summary>
        internal static string Settings_LogFolderNotExist_Message {
            get {
                return ResourceManager.GetString("Settings_LogFolderNotExist_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log folder is not set!.
        /// </summary>
        internal static string Settings_LogFolderNotSet_Message {
            get {
                return ResourceManager.GetString("Settings_LogFolderNotSet_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference screenshot folder is not set!.
        /// </summary>
        internal static string Settings_ReferenceFolderNotSet_Message {
            get {
                return ResourceManager.GetString("Settings_ReferenceFolderNotSet_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review screenshot folder is not set!.
        /// </summary>
        internal static string Settings_ReviewFolderNotSet_Message {
            get {
                return ResourceManager.GetString("Settings_ReviewFolderNotSet_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input text first!.
        /// </summary>
        internal static string TextForm_NotTextInput_Message {
            get {
                return ResourceManager.GetString("TextForm_NotTextInput_Message", resourceCulture);
            }
        }
    }
}
