//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SQL.Loc.OTPCaptureViewer.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SQL.Loc.OTPCaptureViewer.Resx.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About_DialogTitle_Text {
            get {
                return ResourceManager.GetString("About_DialogTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string About_OKButton_Text {
            get {
                return ResourceManager.GetString("About_OKButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tool is for reviewing screen captures for Microsoft Products and Services.
        /// </summary>
        internal static string About_ProductDescription_Text {
            get {
                return ResourceManager.GetString("About_ProductDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ©2017 Microsoft Corporation. All rights reserved..
        /// </summary>
        internal static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Accept.
        /// </summary>
        internal static string EulaForm_AcceptButton_Text {
            get {
                return ResourceManager.GetString("EulaForm_AcceptButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Decline.
        /// </summary>
        internal static string EulaForm_DeclineButton_Text {
            get {
                return ResourceManager.GetString("EulaForm_DeclineButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End User License Agreement.
        /// </summary>
        internal static string EulaForm_DialogTitle_Text {
            get {
                return ResourceManager.GetString("EulaForm_DialogTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EulaForm_EulaText {
            get {
                return ResourceManager.GetString("EulaForm_EulaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fail.
        /// </summary>
        internal static string Main_CaptureResult_Fail_LabelText {
            get {
                return ResourceManager.GetString("Main_CaptureResult_Fail_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Reviewed.
        /// </summary>
        internal static string Main_CaptureResult_NotReviewed_LabelText {
            get {
                return ResourceManager.GetString("Main_CaptureResult_NotReviewed_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pass.
        /// </summary>
        internal static string Main_CaptureResult_Pass_LabelText {
            get {
                return ResourceManager.GetString("Main_CaptureResult_Pass_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Main_ContextMenu_Copy_Text {
            get {
                return ResourceManager.GetString("Main_ContextMenu_Copy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statusStrip1.
        /// </summary>
        internal static string Main_CurrentTotal_LabelText {
            get {
                return ResourceManager.GetString("Main_CurrentTotal_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Issue.
        /// </summary>
        internal static string Main_IssueList_ContextMenu_OpenIssue_Text {
            get {
                return ResourceManager.GetString("Main_IssueList_ContextMenu_OpenIssue_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        internal static string Main_IssueList_CreateByColumnTitle_Text {
            get {
                return ResourceManager.GetString("Main_IssueList_CreateByColumnTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Main_IssueList_HeadColumnTitle_Text {
            get {
                return ResourceManager.GetString("Main_IssueList_HeadColumnTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string Main_IssueList_IdColumnTitle_Text {
            get {
                return ResourceManager.GetString("Main_IssueList_IdColumnTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues:.
        /// </summary>
        internal static string Main_IssueList_Issues_LabelText {
            get {
                return ResourceManager.GetString("Main_IssueList_Issues_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestone.
        /// </summary>
        internal static string Main_IssueList_MilestoneColumnTitle_Text {
            get {
                return ResourceManager.GetString("Main_IssueList_MilestoneColumnTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string Main_IssueList_StateColumnTitle_Text {
            get {
                return ResourceManager.GetString("Main_IssueList_StateColumnTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Main_IssueList_TitleColumnTitle_Text {
            get {
                return ResourceManager.GetString("Main_IssueList_TitleColumnTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Capture.
        /// </summary>
        internal static string Main_PictureBox_ReferenceCapture_Text {
            get {
                return ResourceManager.GetString("Main_PictureBox_ReferenceCapture_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Capture.
        /// </summary>
        internal static string Main_PictureBox_ReviewCapture_Text {
            get {
                return ResourceManager.GetString("Main_PictureBox_ReviewCapture_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Main_ToolBar_About_Text {
            get {
                return ResourceManager.GetString("Main_ToolBar_About_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Line.
        /// </summary>
        internal static string Main_ToolBar_Line_Text {
            get {
                return ResourceManager.GetString("Main_ToolBar_Line_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Issue.
        /// </summary>
        internal static string Main_ToolBar_NewIssue_Text {
            get {
                return ResourceManager.GetString("Main_ToolBar_NewIssue_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report an issue.
        /// </summary>
        internal static string Main_ToolBar_NewIssue_ToolTip {
            get {
                return ResourceManager.GetString("Main_ToolBar_NewIssue_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next[PageDown].
        /// </summary>
        internal static string Main_ToolBar_Next_Text {
            get {
                return ResourceManager.GetString("Main_ToolBar_Next_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous [PageUp].
        /// </summary>
        internal static string Main_ToolBar_Previous_Text {
            get {
                return ResourceManager.GetString("Main_ToolBar_Previous_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Rectangle.
        /// </summary>
        internal static string Main_ToolBar_Rectangle_Text {
            get {
                return ResourceManager.GetString("Main_ToolBar_Rectangle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Main_ToolBar_Refresh_Text {
            get {
                return ResourceManager.GetString("Main_ToolBar_Refresh_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image.
        /// </summary>
        internal static string Main_ToolBar_SaveImage_Text {
            get {
                return ResourceManager.GetString("Main_ToolBar_SaveImage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Main_ToolBar_Settings_Text {
            get {
                return ResourceManager.GetString("Main_ToolBar_Settings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Main_ToolBar_Start_Text {
            get {
                return ResourceManager.GetString("Main_ToolBar_Start_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Text.
        /// </summary>
        internal static string Main_ToolBar_Text_Text {
            get {
                return ResourceManager.GetString("Main_ToolBar_Text_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in.
        /// </summary>
        internal static string Main_ToolBar_ZoonIn_Text {
            get {
                return ResourceManager.GetString("Main_ToolBar_ZoonIn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        internal static string Main_ToolBar_ZoonOut_Text {
            get {
                return ResourceManager.GetString("Main_ToolBar_ZoonOut_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toolStrip1.
        /// </summary>
        internal static string Main_toolStrip_Text {
            get {
                return ResourceManager.GetString("Main_toolStrip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string NewIssue_CancelButton_Text {
            get {
                return ResourceManager.GetString("NewIssue_CancelButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewIssue.
        /// </summary>
        internal static string NewIssue_DialogTitle_Text {
            get {
                return ResourceManager.GetString("NewIssue_DialogTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string NewIssue_IssueDescription_LabelText {
            get {
                return ResourceManager.GetString("NewIssue_IssueDescription_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string NewIssue_IssueTitle_LabelText {
            get {
                return ResourceManager.GetString("NewIssue_IssueTitle_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NewIssue_Separator1_Text {
            get {
                return ResourceManager.GetString("NewIssue_Separator1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string NewIssue_SubmitButton_Text {
            get {
                return ResourceManager.GetString("NewIssue_SubmitButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NewIssue_toggleButtonAlignCenter_Text {
            get {
                return ResourceManager.GetString("NewIssue_toggleButtonAlignCenter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NewIssue_toggleButtonAlignLeft_Text {
            get {
                return ResourceManager.GetString("NewIssue_toggleButtonAlignLeft_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NewIssue_toggleButtonAlignRight_Text {
            get {
                return ResourceManager.GetString("NewIssue_toggleButtonAlignRight_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NewIssue_toggleButtonBar_Text {
            get {
                return ResourceManager.GetString("NewIssue_toggleButtonBar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NewIssue_toggleButtonBold_Text {
            get {
                return ResourceManager.GetString("NewIssue_toggleButtonBold_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NewIssue_toggleButtonBulletList_Text {
            get {
                return ResourceManager.GetString("NewIssue_toggleButtonBulletList_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NewIssue_toggleButtonItalic_Text {
            get {
                return ResourceManager.GetString("NewIssue_toggleButtonItalic_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NewIssue_toggleButtonJustify_Text {
            get {
                return ResourceManager.GetString("NewIssue_toggleButtonJustify_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NewIssue_toggleButtonNumberedList_Text {
            get {
                return ResourceManager.GetString("NewIssue_toggleButtonNumberedList_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NewIssue_toggleButtonUnderline_Text {
            get {
                return ResourceManager.GetString("NewIssue_toggleButtonUnderline_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Test Platform Capture Viewer.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Test Platform Capture Viewer - Preview.
        /// </summary>
        internal static string ProductName_Preview {
            get {
                return ResourceManager.GetString("ProductName_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string RepoBrowser_CancelButton_Text {
            get {
                return ResourceManager.GetString("RepoBrowser_CancelButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse folder.
        /// </summary>
        internal static string RepoBrowser_DialogTitle_Text {
            get {
                return ResourceManager.GetString("RepoBrowser_DialogTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string RepoBrowser_OKButton_Text {
            get {
                return ResourceManager.GetString("RepoBrowser_OKButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the token.
        /// </summary>
        internal static string Setting_ShowTheTokenCheckBox_Text {
            get {
                return ResourceManager.GetString("Setting_ShowTheTokenCheckBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github Access Token:.
        /// </summary>
        internal static string Settings_AccessTokenLable_Text {
            get {
                return ResourceManager.GetString("Settings_AccessTokenLable_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        internal static string Settings_Authentication_GroupName {
            get {
                return ResourceManager.GetString("Settings_Authentication_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string Settings_BrowserButton_Text {
            get {
                return ResourceManager.GetString("Settings_BrowserButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Settings_CancelButton_Text {
            get {
                return ResourceManager.GetString("Settings_CancelButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Info.
        /// </summary>
        internal static string Settings_CaptureInfo_GroupName {
            get {
                return ResourceManager.GetString("Settings_CaptureInfo_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Capture Folder:.
        /// </summary>
        internal static string Settings_CaptureInfo_ReferenceFolderLabel_Text {
            get {
                return ResourceManager.GetString("Settings_CaptureInfo_ReferenceFolderLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Capture Folder:.
        /// </summary>
        internal static string Settings_CaptureInfo_ReviewFolderLabel_Text {
            get {
                return ResourceManager.GetString("Settings_CaptureInfo_ReviewFolderLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save reference capture side by side with review capture.
        /// </summary>
        internal static string Settings_CheckBoxSaveSxS_Text {
            get {
                return ResourceManager.GetString("Settings_CheckBoxSaveSxS_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Settings_ConnectButton_Text {
            get {
                return ResourceManager.GetString("Settings_ConnectButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_DialogTitle {
            get {
                return ResourceManager.GetString("Settings_DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Folder:.
        /// </summary>
        internal static string Settings_LogFolderLabel_Text {
            get {
                return ResourceManager.GetString("Settings_LogFolderLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Settings_OKButton_Text {
            get {
                return ResourceManager.GetString("Settings_OKButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string TextForm_CancelButton_Text {
            get {
                return ResourceManager.GetString("TextForm_CancelButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Text.
        /// </summary>
        internal static string TextForm_DialogTitle_Text {
            get {
                return ResourceManager.GetString("TextForm_DialogTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string TextForm_SubmitButton_Text {
            get {
                return ResourceManager.GetString("TextForm_SubmitButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.3.0.0.
        /// </summary>
        internal static string VersionNumber {
            get {
                return ResourceManager.GetString("VersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitForm.
        /// </summary>
        internal static string WaitForm_DialogTitle_Text {
            get {
                return ResourceManager.GetString("WaitForm_DialogTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        internal static string WaitForm_Processing_Text {
            get {
                return ResourceManager.GetString("WaitForm_Processing_Text", resourceCulture);
            }
        }
    }
}
